//! macOS packet-filter (PF) blocking — the layer that makes a block hold.
//!
//! The hosts file only intercepts names that go through the system resolver.
//! Three common things walk straight past it:
//!
//!   * **DNS-over-HTTPS.** Chrome and Firefox resolve names over HTTPS to
//!     1.1.1.1 or 8.8.8.8 and never consult `/etc/hosts` at all.
//!   * **Raw IPs**, and links that already carry one.
//!   * **Cached connections** that were open before the block started.
//!
//! So, like SelfControl, we also block at the packet level: resolve each domain
//! to its addresses up front and tell PF to refuse traffic to them. We go one
//! further and block the well-known DoH resolvers on 443, which SelfControl
//! leaves open — with DoH unavailable, browsers fall back to the system
//! resolver, where the hosts file is waiting.
//!
//! Safety rules this module holds itself to:
//!   * Never rewrite a user's PF config — only append our own anchor, and only
//!     if it isn't already referenced.
//!   * Only disable PF if *we* enabled it, via the token `pfctl -E` hands back.
//!     Someone may be running Little Snitch or a corporate firewall.
//!   * Never block port 53, or DNS itself would break.
//!   * Best-effort: if PF is unavailable the hosts block still stands, so a
//!     failure here must not fail the session.

#![cfg(target_os = "macos")]

use std::collections::BTreeSet;
use std::net::{IpAddr, ToSocketAddrs};
use std::path::Path;
use std::process::Command;

pub const ANCHOR: &str = "lock.in";
pub const ANCHOR_FILE: &str = "/etc/pf.anchors/lock.in";
pub const PF_CONF: &str = "/etc/pf.conf";
pub const TOKEN_FILE: &str = "/etc/lock.in.pf.token";

const BEGIN: &str = "# >>> lock.in anchor >>>";
const END: &str = "# <<< lock.in anchor <<<";

/// Resolvers that serve DNS-over-HTTPS. Blocked on 443 only — port 53 stays
/// open so ordinary DNS (and therefore the hosts file) keeps working.
pub const DOH_RESOLVERS: &[&str] = &[
    // Cloudflare (Firefox's default DoH provider)
    "1.1.1.1",
    "1.0.0.1",
    "2606:4700:4700::1111",
    "2606:4700:4700::1001",
    // Google (Chrome's, when your system DNS is already Google)
    "8.8.8.8",
    "8.8.4.4",
    "2001:4860:4860::8888",
    "2001:4860:4860::8844",
    // Quad9
    "9.9.9.9",
    "149.112.112.112",
    // OpenDNS
    "208.67.222.222",
    "208.67.220.220",
    // AdGuard
    "94.140.14.14",
    "94.140.15.15",
];

/// Look up every address a domain currently answers with, v4 and v6.
///
/// Port 0 with `to_socket_addrs` is just the idiomatic way to ask the resolver
/// for a host's addresses. Failures are silent on purpose: a domain that
/// doesn't resolve has nothing to block at the IP layer, and the hosts entry
/// covers it anyway.
pub fn resolve(domain: &str) -> Vec<IpAddr> {
    let mut out = Vec::new();
    if let Ok(addrs) = (domain, 0u16).to_socket_addrs() {
        for a in addrs {
            out.push(a.ip());
        }
    }
    out
}

/// PF rules blocking all traffic to `ips`, plus 443 to the DoH resolvers.
///
/// `block return` rather than a silent drop so the browser says "can't connect"
/// straight away instead of hanging for thirty seconds — a timeout invites you
/// to sit there retrying, which is the opposite of what a focus tool wants.
pub fn build_anchor(ips: &[IpAddr], doh: &[&str]) -> String {
    let mut out = String::new();
    out.push_str("# Generated by lock.in. Replaced on every session; removed when it ends.\n");
    out.push_str("set block-policy return\n");
    out.push_str("set skip on lo0\n\n");

    // Sorted + deduped so the file is stable between runs and easy to diff.
    let unique: BTreeSet<String> = ips.iter().map(|ip| ip.to_string()).collect();
    if !unique.is_empty() {
        out.push_str("# Sites you asked to block, by address\n");
        for ip in &unique {
            out.push_str(&format!("block return out quick proto tcp from any to {ip}\n"));
            out.push_str(&format!("block return out quick proto udp from any to {ip}\n"));
        }
        out.push('\n');
    }

    if !doh.is_empty() {
        out.push_str("# DNS-over-HTTPS resolvers, port 443 only, so browsers fall back to\n");
        out.push_str("# system DNS where the hosts file applies. Port 53 stays open.\n");
        for r in doh {
            out.push_str(&format!(
                "block return out quick proto tcp from any to {r} port 443\n"
            ));
            out.push_str(&format!(
                "block return out quick proto udp from any to {r} port 443\n"
            ));
        }
    }
    out
}

/// Add our anchor to pf.conf if it isn't referenced yet, leaving the rest alone.
pub fn ensure_anchor_in_conf(conf: &str) -> String {
    if conf.contains(ANCHOR_FILE) {
        return conf.to_string();
    }
    let mut out = conf.to_string();
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(BEGIN);
    out.push('\n');
    out.push_str(&format!("anchor \"{ANCHOR}\"\n"));
    out.push_str(&format!("load anchor \"{ANCHOR}\" from \"{ANCHOR_FILE}\"\n"));
    out.push_str(END);
    out.push('\n');
    out
}

/// Remove our anchor lines from pf.conf, leaving every other rule untouched.
pub fn remove_anchor_from_conf(conf: &str) -> String {
    let mut out: Vec<&str> = Vec::new();
    let mut skipping = false;
    for line in conf.lines() {
        let t = line.trim();
        if t == BEGIN {
            skipping = true;
            continue;
        }
        if t == END {
            skipping = false;
            continue;
        }
        if skipping {
            continue;
        }
        // Also catch lines from an older layout that lacked the markers.
        if t.contains(ANCHOR_FILE) || t == format!("anchor \"{ANCHOR}\"") {
            continue;
        }
        out.push(line);
    }
    let mut joined = out.join("\n");
    while joined.ends_with('\n') {
        joined.pop();
    }
    joined.push('\n');
    joined
}

/// Pull the token out of `pfctl -E` output, e.g. "Token : 12345678".
pub fn parse_token(output: &str) -> Option<String> {
    for line in output.lines() {
        if let Some((label, value)) = line.split_once(':') {
            if label.trim().eq_ignore_ascii_case("token") {
                let t = value.trim();
                if !t.is_empty() {
                    return Some(t.to_string());
                }
            }
        }
    }
    None
}

// --- Side-effecting operations (root required) ---

fn pfctl(args: &[&str]) -> Result<String, String> {
    let out = Command::new("/sbin/pfctl")
        .args(args)
        .output()
        .map_err(|e| format!("couldn't run pfctl: {e}"))?;
    // pfctl writes almost everything, including the token, to stderr.
    let mut combined = String::from_utf8_lossy(&out.stderr).to_string();
    combined.push_str(&String::from_utf8_lossy(&out.stdout));
    if out.status.success() {
        Ok(combined)
    } else {
        Err(combined)
    }
}

/// Install PF rules for `domains`. Best-effort: an error here is reported but
/// shouldn't abort the session, because the hosts block is already in place.
pub fn start(domains: &[String]) -> Result<(), String> {
    let mut ips: Vec<IpAddr> = Vec::new();
    for d in domains {
        ips.extend(resolve(d));
        ips.extend(resolve(&format!("www.{d}")));
    }

    let anchor_body = build_anchor(&ips, DOH_RESOLVERS);
    if let Some(dir) = Path::new(ANCHOR_FILE).parent() {
        std::fs::create_dir_all(dir).map_err(|e| format!("couldn't create {dir:?}: {e}"))?;
    }
    std::fs::write(ANCHOR_FILE, anchor_body)
        .map_err(|e| format!("couldn't write {ANCHOR_FILE}: {e}"))?;

    let conf = std::fs::read_to_string(PF_CONF).map_err(|e| format!("couldn't read pf.conf: {e}"))?;
    let updated = ensure_anchor_in_conf(&conf);
    if updated != conf {
        std::fs::write(PF_CONF, &updated).map_err(|e| format!("couldn't write pf.conf: {e}"))?;
    }

    // -E enables PF and returns a token; -F states drops connections that were
    // already open to a site you've just blocked.
    let out = pfctl(&["-E", "-f", PF_CONF, "-F", "states"])?;
    if let Some(token) = parse_token(&out) {
        let _ = std::fs::write(TOKEN_FILE, token);
    }
    Ok(())
}

/// Remove our rules and release our reference to PF.
pub fn stop() -> Result<(), String> {
    // Empty the anchor first, so traffic is flowing again even if a later step
    // fails and leaves the anchor loaded.
    let _ = std::fs::write(ANCHOR_FILE, "# lock.in: no active block\n");

    if let Ok(conf) = std::fs::read_to_string(PF_CONF) {
        let cleaned = remove_anchor_from_conf(&conf);
        if cleaned != conf {
            let _ = std::fs::write(PF_CONF, &cleaned);
        }
    }

    // Release only our own enable reference. If something else turned PF on --
    // Little Snitch, a corporate firewall -- it stays on, which is why we don't
    // just call `pfctl -d`.
    match std::fs::read_to_string(TOKEN_FILE) {
        Ok(token) if !token.trim().is_empty() => {
            let _ = pfctl(&["-X", token.trim(), "-f", PF_CONF]);
        }
        _ => {
            let _ = pfctl(&["-f", PF_CONF]);
        }
    }
    let _ = std::fs::remove_file(TOKEN_FILE);
    Ok(())
}

/// Whether our anchor is currently loaded with real rules.
pub fn is_active() -> bool {
    match pfctl(&["-a", ANCHOR, "-s", "rules"]) {
        Ok(rules) => rules.lines().any(|l| l.trim_start().starts_with("block")),
        Err(_) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn anchor_blocks_each_address_on_tcp_and_udp() {
        let ips: Vec<IpAddr> = vec!["1.2.3.4".parse().unwrap(), "::ffff:5.6.7.8".parse().unwrap()];
        let a = build_anchor(&ips, &[]);
        assert!(a.contains("block return out quick proto tcp from any to 1.2.3.4"));
        assert!(a.contains("block return out quick proto udp from any to 1.2.3.4"));
        assert!(a.contains("set skip on lo0"), "loopback must stay usable");
    }

    #[test]
    fn doh_resolvers_are_blocked_only_on_443() {
        let a = build_anchor(&[], &["1.1.1.1"]);
        assert!(a.contains("block return out quick proto tcp from any to 1.1.1.1 port 443"));
        // Port 53 must never be blocked or name resolution dies entirely.
        assert!(!a.contains("port 53"));
    }

    #[test]
    fn addresses_are_deduped_and_ordered() {
        let ips: Vec<IpAddr> = vec![
            "9.9.9.9".parse().unwrap(),
            "1.2.3.4".parse().unwrap(),
            "1.2.3.4".parse().unwrap(),
        ];
        let a = build_anchor(&ips, &[]);
        assert_eq!(a.matches("to 1.2.3.4\n").count(), 2, "one tcp + one udp only");
        let first = a.find("1.2.3.4").unwrap();
        let second = a.find("9.9.9.9").unwrap();
        assert!(first < second, "sorted output keeps the file stable");
    }

    #[test]
    fn empty_blocklist_still_shuts_the_doh_door() {
        let a = build_anchor(&[], DOH_RESOLVERS);
        assert!(a.contains("1.1.1.1"));
        assert!(a.contains("8.8.8.8"));
    }

    #[test]
    fn anchor_is_added_once_and_only_once() {
        let conf = "scrub-anchor \"com.apple/*\"\nnat-anchor \"com.apple/*\"\n";
        let once = ensure_anchor_in_conf(conf);
        let twice = ensure_anchor_in_conf(&once);
        assert_eq!(once, twice, "re-running must not stack anchors");
        assert_eq!(once.matches(ANCHOR_FILE).count(), 2, "anchor + load lines");
    }

    #[test]
    fn existing_pf_rules_survive_a_round_trip() {
        let conf = "scrub-anchor \"com.apple/*\"\nnat-anchor \"com.apple/*\"\ndummynet-anchor \"com.apple/*\"\n";
        let restored = remove_anchor_from_conf(&ensure_anchor_in_conf(conf));
        assert!(restored.contains("scrub-anchor \"com.apple/*\""));
        assert!(restored.contains("dummynet-anchor \"com.apple/*\""));
        assert!(!restored.contains(ANCHOR_FILE));
    }

    #[test]
    fn removal_also_cleans_up_unmarked_legacy_lines() {
        let conf = format!("anchor \"com.apple/*\"\nanchor \"{ANCHOR}\"\nload anchor \"{ANCHOR}\" from \"{ANCHOR_FILE}\"\n");
        let cleaned = remove_anchor_from_conf(&conf);
        assert!(cleaned.contains("anchor \"com.apple/*\""));
        assert!(!cleaned.contains(ANCHOR_FILE));
    }

    #[test]
    fn token_is_read_from_pfctl_chatter() {
        let out = "No ALTQ support in kernel\nALTQ related functions disabled\nToken : 4113325891163534848\n";
        assert_eq!(parse_token(out).as_deref(), Some("4113325891163534848"));
        assert_eq!(parse_token("pf enabled"), None);
    }
}
